name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build and deploy
        run: |
          go build -o app
          npx netlify deploy --prod --dir=. --functions=app
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK }}
